// One-shot helper: parses the Google Fonts CSS, keeps only latin + latin-ext
// subsets, downloads WOFF2 files into fonts/, and emits local @font-face rules
// to fonts/fonts.css. Not run during deploy — this is a tool for the 0b step.
//
// Usage: node _scripts/extract-fonts.js

const fs = require('fs');
const path = require('path');
const https = require('https');

const KEEP_SUBSETS = new Set(['latin', 'latin-ext']);
// Typography lock (Apr 2026):
//   serif → Libre Caslon Text (the type the Constitution was first printed in)
//   sans  → Public Sans       (USWDS-commissioned federal typeface)
//   mono  → Courier Prime     (typewriter / mid-century officialdom register)
// All three OFL, all latin + latin-ext only. Weights kept tight on serif/mono
// because Google Fonts only serves these as static; intermediate weights are
// browser-synthesised (600 → 700 for serif headings is acceptable).
const CSS_URL =
  'https://fonts.googleapis.com/css2' +
  '?family=Libre+Caslon+Text:ital,wght@0,400;0,700;1,400' +
  '&family=Public+Sans:wght@400;500;600;700' +
  '&family=Courier+Prime:ital,wght@0,400;0,700;1,400' +
  '&display=swap';

const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36';

const root = path.resolve(__dirname, '..');
const fontsDir = path.join(root, 'fonts');

function fetchText(url) {
  return new Promise((resolve, reject) => {
    https
      .get(url, { headers: { 'User-Agent': UA } }, (res) => {
        if (res.statusCode !== 200) {
          reject(new Error(`HTTP ${res.statusCode} for ${url}`));
          return;
        }
        let buf = '';
        res.setEncoding('utf8');
        res.on('data', (c) => (buf += c));
        res.on('end', () => resolve(buf));
      })
      .on('error', reject);
  });
}

function fetchBinary(url, dest) {
  return new Promise((resolve, reject) => {
    const file = fs.createWriteStream(dest);
    https
      .get(url, { headers: { 'User-Agent': UA } }, (res) => {
        if (res.statusCode !== 200) {
          reject(new Error(`HTTP ${res.statusCode} for ${url}`));
          return;
        }
        res.pipe(file);
        file.on('finish', () => file.close(resolve));
      })
      .on('error', (err) => {
        fs.unlink(dest, () => reject(err));
      });
  });
}

function slug(family) {
  return family.toLowerCase().replace(/\s+/g, '-');
}

function parseBlocks(css) {
  // Split on /* comment */ markers that precede each @font-face rule
  const blocks = [];
  const re = /\/\*\s*([^*]+?)\s*\*\/\s*@font-face\s*{([^}]+)}/g;
  let m;
  while ((m = re.exec(css)) !== null) {
    const subset = m[1].trim();
    const body = m[2];
    const family = /font-family:\s*'([^']+)'/.exec(body)?.[1];
    const style = /font-style:\s*([^;]+);/.exec(body)?.[1].trim();
    const weight = /font-weight:\s*(\d+)/.exec(body)?.[1];
    const src = /src:\s*url\(([^)]+)\)/.exec(body)?.[1];
    const unicode = /unicode-range:\s*([^;]+);/.exec(body)?.[1].trim();
    if (!family || !src || !style || !weight || !unicode) continue;
    blocks.push({ subset, family, style, weight, src, unicode });
  }
  return blocks;
}

function localName(b) {
  // e.g. inter-tight-400-normal-latin.woff2
  const styleSuffix = b.style === 'italic' ? 'italic' : 'normal';
  return `${slug(b.family)}-${b.weight}-${styleSuffix}-${b.subset}.woff2`;
}

function buildCss(blocks) {
  const lines = [
    '/* Self-hosted Google Fonts (latin + latin-ext subsets). */',
    '/* Generated by _scripts/extract-fonts.js — do not edit by hand. */',
    '',
  ];
  for (const b of blocks) {
    lines.push(`/* ${b.subset} */`);
    lines.push('@font-face {');
    lines.push(`  font-family: '${b.family}';`);
    lines.push(`  font-style: ${b.style};`);
    lines.push(`  font-weight: ${b.weight};`);
    lines.push(`  font-display: swap;`);
    lines.push(`  src: url('fonts/${localName(b)}') format('woff2');`);
    lines.push(`  unicode-range: ${b.unicode};`);
    lines.push('}');
  }
  return lines.join('\n') + '\n';
}

(async () => {
  console.log(`Fetching ${CSS_URL}`);
  const css = await fetchText(CSS_URL);
  const allBlocks = parseBlocks(css);
  console.log(`Parsed ${allBlocks.length} @font-face blocks total`);

  const kept = allBlocks.filter((b) => KEEP_SUBSETS.has(b.subset));
  console.log(`Keeping ${kept.length} blocks (subsets: ${[...KEEP_SUBSETS].join(', ')})`);

  if (!fs.existsSync(fontsDir)) fs.mkdirSync(fontsDir, { recursive: true });

  for (const b of kept) {
    const dest = path.join(fontsDir, localName(b));
    if (fs.existsSync(dest)) {
      console.log(`  skip (exists): ${localName(b)}`);
      continue;
    }
    console.log(`  download: ${localName(b)}`);
    await fetchBinary(b.src, dest);
  }

  const outCss = buildCss(kept);
  const outPath = path.join(fontsDir, 'fonts.css');
  fs.writeFileSync(outPath, outCss);
  console.log(`Wrote ${outPath} (${outCss.length} bytes)`);
})().catch((e) => {
  console.error(e);
  process.exit(1);
});
